version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  finalreceiver: &base
    image: golang:1.16-alpine
    command: go run ./finalreceiver
    working_dir: /go/src/app
    volumes: 
      - ".:/go/src/app"
    environment: 
      REDIS_ADDR: redis:6379 

  initialsender: 
    <<: *base
    command: go run ./initialsender
    ports:
      - 8080:8080

  pipfilterA:
    <<: *base
    command: go run ./pipefilterA
  
  pipfilterB:
    <<: *base
    command: go run ./pipefilterB
  
